### ISSUE TITLE
WSDL tools call gives one argument too little error

### ISSUE THREAD

**Issue by npklein** [npklein/miP3#1]
The error message:

> [main] User-agent: EBI-Sample-Client/2760 (iprscan_soappy.pyc; Python 2.7.14; Windows)
> 
> [main] WSDL: http://www.ebi.ac.uk/Tools/services/soap/iprscan5?wsdl
> 
> Traceback (most recent call last):
> 
>   File "miP3.py", line 309, in <module>
> 
>     subject_info_filtered_on_domains = interpro_scanner.interproScan(subject_info_filtered_on_compared_length, all_proteins,pfam_domains_file_path, args['email'], developing, script_path)  # filter on domain information gained from interproscan
> 
>   File "D:\miP3-master\interpro_scanner.py", line 137, in interproScan
> 
>     interpro_data = interpro_result(interpro_submit_sequences, email, developing, script_dir)
> 
>   File "D:\miP3-master\interpro_scanner.py", line 41, in interpro_result
> 
>     for protein_name, interpro_result in iprscan_soappy.runInterpro(interpro_submit_sequences, email):
> 
>                 # get dict with as value protein name and as value various stuff
> 
>   File "D:\miP3-master\iprscan_soappy.py", line 406, in runInterpro
> 
>     verbose = True, write_outfiles = False, quiet = False, debugLevel = 1)     # write out any of the results, because it gets parsed directly
> 
>   File "D:\miP3-master\iprscan_soappy.py", line 117, in __init__
> 
>     self.server = WSDL.Proxy(WSDLUrl)
> 
>   File "C:\Python27\lib\site-packages\SOAPpy\WSDL.py", line 97, in __init__
> 
>     callinfo = wstools.WSDLTools.callInfoFromWSDL(port, operation.name)
> 
> TypeError: callInfoFromWSDL() takes exactly 3 arguments (2 given)
> 
> ========================================
> 
> 0:00:03.031 - End Program
> 
> Elapsed time: 0:00:03.030

**Comment by npklein** [comment]
Works for WSDL tools 0.4.3, but not for 0.4.5
See also https://github.com/grangier/python-soappy/issues/2 and https://github.com/pycontribs/wstools/issues/19

**Comment by npklein** [comment]
Fix: use version 0.4.3 of wsdl tools. Install with 

    pip install -Iv wstools==0.4.3
