### ISSUE TITLE
KeyError: 'iprscan5-S20210902-141018-0225-81914800-p1m'

### ISSUE THREAD

**Issue by sanjaysingh765** [npklein/miP3#2]
Hi,

Whenever I run the program with the example dataset it finishes without any error but I am getting following error with my dataset. 

```
Traceback (most recent call last):
  File "miP3.py", line 309, in <module>
    subject_info_filtered_on_domains = interpro_scanner.interproScan(subject_info_filtered_on_compared_length, all_proteins,pfam_domains_file_path, args['email'], developing, script_path)  # filter on domain information gained from interproscan
  File "/home/sanjay/Desktop/miP3-1.1/interpro_scanner.py", line 121, in interproScan
    interpro_data = interpro_result(interpro_submit_sequences,email,developing, script_dir)
  File "/home/sanjay/Desktop/miP3-1.1/interpro_scanner.py", line 41, in interpro_result
    for protein_name, interpro_result in iprscan_soappy.runInterpro(interpro_submit_sequences, email):					# get dict with as value protein name and as value various stuff
  File "/home/sanjay/Desktop/miP3-1.1/iprscan_soappy.py", line 450, in runInterpro
    yield interproscan.getSequenceNameForJobID(jobid), interpro_result
  File "/home/sanjay/Desktop/miP3-1.1/iprscan_soappy.py", line 237, in getSequenceNameForJobID
    return(self.sequence_name_for_job_id[jobid])
KeyError: 'iprscan5-S20210902-141018-0225-81914800-p1m'
```
Thanks

**Comment by npklein** [comment]
Would it be possbile to upload (example/test) data with which you get this error, so that I can test it?

**Comment by sanjaysingh765** [comment]
> Would it be possbile to upload (example/test) data with which you get this error, so that I can test it?

Program finish without any error for the  .test files but it though error when I try with contigs-l550.test and tf.fasta. You can access files here 
https://drive.google.com/drive/folders/1YOK1CSIsVcgJgGz7xDw4pue-SKiQ9Tx2?usp=sharing
Thanks

**Comment by npklein** [comment]
I have requested access, can you grant it?

**Comment by sanjaysingh765** [comment]
> I have requested access, can you grant it?

I just did it. Sorry for the delay.

**Comment by sanjaysingh765** [comment]
Wonder if you get time to look into error. Thanks

**Comment by npklein** [comment]
Should be fixed in latest commit(https://github.com/npklein/miP3/commit/53a9ec0dd1fd092e06a27260bff3a7136429c910)
